/* Cutover redirects for www.the-training-centre.com.
 *
 * Generated by scratchpad/gen_middleware.py from a live inventory of the old
 * Arlo site: every URL below was fetched and returned 200 before being mapped,
 * and each was paired to its new page by joining Arlo's template IDs to the
 * SLUGS/HANDBUILT maps in _build_pages.py.
 *
 * This lives in a Function rather than _redirects because Cloudflare Pages
 * applies only the first 100 rules of a _redirects file and silently ignores
 * the rest. The inventory is larger than that.
 *
 * Order: Arlo's own paths first (they must never be swallowed by the new site),
 * then exact content URLs, then prefix fallbacks, then straight through to the
 * static asset.
 */

/* Paths Arlo still owns after the domain moves: booking, checkout, the customer
   portal and the public API. Old booking links, bookmarked checkouts and the
   links inside Arlo's own confirmation emails keep working because of these. */
const ARLO = "https://marketstreetconsultantsltdevents.arlo.co";
const ARLO_PREFIXES = [
  "/uk/register", "/uk/checkout", "/uk/account", "/uk/orders",
  "/eu/register", "/eu/checkout", "/api",
];

/* Old URL -> page on the new site. 112 entries + the two bare listing URLs below. */
const EXACT = {
  // Bare listing pages (no trailing slash) are real live URLs on the old site
  // (302 -> /w/uk/...). Without these they fell through to the "/uk/" catch-all
  // and landed on the homepage instead of the equivalent listing. (31 Jul review)
  "/uk/presenters": "/trainers/",
  "/uk/venues": "/schedule/",
  "/uk/courses/108-lead-disaster-recovery-manager": "/courses/lead-disaster-recovery-manager/",
  "/uk/courses/11-european-data-protection-privacy-programme-management-dpo-ready": "/courses/dpo-ready/",
  "/uk/courses/111-certified-iso-27035-lead-incident-manager": "/courses/iso-27035-lead-incident-manager/",
  "/uk/courses/116-certified-cyber-security-analyst": "/courses/cyber-security-analyst/",
  "/uk/courses/12-certified-information-privacy-professional-cipp-e": "/courses/cipp-e/",
  "/uk/courses/13-certified-information-privacy-manager-cipm": "/courses/cipm/",
  "/uk/courses/149-certified-information-privacy-auditor-cipa": "/courses/cipa/",
  "/uk/courses/150-ai-governance-professional-aigp": "/courses/aigp/",
  "/uk/courses/151-certified-iso-22361-lead-crisis-manager": "/courses/iso-22361-lead-crisis-manager/",
  "/uk/courses/153-iso-42001-lead-implementer": "/courses/iso-42001-lead-implementer/",
  "/uk/courses/154-iso-42001-lead-auditor": "/courses/iso-42001-lead-auditor/",
  "/uk/courses/161-certified-operational-resilience-manager": "/courses/operational-resilience-manager/",
  "/uk/courses/162-bcs-essentials-in-artificial-intelligence": "/courses/bcs-essentials-ai/",
  "/uk/courses/163-bcs-foundation-certificate-in-artificial-intelligence": "/courses/bcs-foundation-ai/",
  "/uk/courses/170-certified-cyber-assurance-practitioner": "/courses/cyber-assurance-practitioner/",
  "/uk/courses/171-cyber-security-foundation": "/courses/cyber-security-foundation/",
  "/uk/courses/173-certified-information-privacy-professional-study-guide-hard-copy": "/courses/cipp-e/",
  "/uk/courses/174-artificial-intelligence-for-project-managers": "/courses/ai-for-project-managers/",
  "/uk/courses/175-ai-productivity-foundation-practitioner": "/courses/ai-productivity/",
  "/uk/courses/176-ai-agents-foundation-practitioner": "/courses/ai-agents/",
  "/uk/courses/177-ai-strategy-governance-foundation-and-practitioner": "/courses/ai-strategy-governance/",
  "/uk/courses/178-trusted-ai-safety-expert-taise": "/courses/taise/",
  "/uk/courses/18-certified-is0-27001-lead-implementer": "/courses/iso-27001-lead-implementer/",
  "/uk/courses/19-certified-iso-27001-lead-auditor": "/courses/iso-27001-lead-auditor/",
  "/uk/courses/22-certified-data-protection-officer-training-cdpo": "/courses/cdpo/",
  "/uk/courses/23-certified-gdpr-foundation": "/courses/gdpr-foundation/",
  "/uk/courses/25-certified-iso-31000-lead-risk-manager": "/courses/iso-31000-lead-risk-manager/",
  "/uk/courses/31-certified-iso-22301-lead-auditor": "/courses/iso-22301-lead-auditor/",
  "/uk/courses/32-certified-iso-22301-lead-implementer": "/courses/iso-22301-lead-implementer/",
  "/uk/courses/41-certified-information-privacy-technologist-cipt": "/courses/cipt/",
  "/uk/courses/42-certified-cybersecurity-manager": "/courses/cybersecurity-manager/",
  "/uk/courses/47-certified-iso-27701-lead-implementer": "/courses/iso-27701-lead-implementer/",
  "/uk/courses/63-gdpr-awareness-training": "/courses/gdpr-awareness/",
  "/uk/courses/92-iso-27005-information-security-risk-manager": "/courses/iso-27005-risk-manager/",
  "/uk/courses/94-certified-iso-31000-risk-analyst": "/courses/iso-31000-risk-analyst/",
  "/uk/presenters/10-frank-turley": "/trainers/",
  "/uk/presenters/12-kevin-thomason": "/trainers/",
  "/uk/presenters/174-stuart-wright": "/trainers/",
  "/uk/presenters/181-saj-hussein": "/trainers/",
  "/uk/presenters/2-john-mcglone": "/trainers/",
  "/uk/presenters/2262-william-bello": "/trainers/",
  "/uk/presenters/8-evonne-gourlay": "/trainers/",
  "/uk/presenters/9-ishrat-pasha": "/trainers/",
  "/uk/venues/16-belgian-office": "/schedule/",
  "/uk/venues/24-marble-arch": "/schedule/",
  "/uk/venues/25-dubai-office": "/schedule/",
  "/uk/venues/26-riyadh-office": "/schedule/",
  "/uk/venues/27-stirling": "/schedule/",
  "/uk/venues/28-minories": "/schedule/",
  "/uk/venues/29-double-tree-by-hilton-manchester": "/schedule/",
  "/uk/venues/3-manchester-novotel": "/schedule/",
  "/uk/venues/30-signing-tree": "/schedule/",
  "/uk/venues/4-prospero-house": "/schedule/",
  "/uk/venues/5-edinburgh": "/schedule/",
  "/w/uk": "/",
  "/w/uk/aboutus": "/about/",
  "/w/uk/courses": "/courses/",
  "/w/uk/courses/108-lead-disaster-recovery-manager": "/courses/lead-disaster-recovery-manager/",
  "/w/uk/courses/11-european-data-protection-privacy-programme-management-dpo-ready": "/courses/dpo-ready/",
  "/w/uk/courses/111-certified-iso-27035-lead-incident-manager": "/courses/iso-27035-lead-incident-manager/",
  "/w/uk/courses/116-certified-cyber-security-analyst": "/courses/cyber-security-analyst/",
  "/w/uk/courses/12-certified-information-privacy-professional-cipp-e": "/courses/cipp-e/",
  "/w/uk/courses/13-certified-information-privacy-manager-cipm": "/courses/cipm/",
  "/w/uk/courses/149-certified-information-privacy-auditor-cipa": "/courses/cipa/",
  "/w/uk/courses/150-ai-governance-professional-aigp": "/courses/aigp/",
  "/w/uk/courses/151-certified-iso-22361-lead-crisis-manager": "/courses/iso-22361-lead-crisis-manager/",
  "/w/uk/courses/153-iso-42001-lead-implementer": "/courses/iso-42001-lead-implementer/",
  "/w/uk/courses/154-iso-42001-lead-auditor": "/courses/iso-42001-lead-auditor/",
  "/w/uk/courses/161-certified-operational-resilience-manager": "/courses/operational-resilience-manager/",
  "/w/uk/courses/162-bcs-essentials-in-artificial-intelligence": "/courses/bcs-essentials-ai/",
  "/w/uk/courses/163-bcs-foundation-certificate-in-artificial-intelligence": "/courses/bcs-foundation-ai/",
  "/w/uk/courses/170-certified-cyber-assurance-practitioner": "/courses/cyber-assurance-practitioner/",
  "/w/uk/courses/171-cyber-security-foundation": "/courses/cyber-security-foundation/",
  "/w/uk/courses/173-certified-information-privacy-professional-study-guide-hard-copy": "/courses/cipp-e/",
  "/w/uk/courses/174-artificial-intelligence-for-project-managers": "/courses/ai-for-project-managers/",
  "/w/uk/courses/175-ai-productivity-foundation-practitioner": "/courses/ai-productivity/",
  "/w/uk/courses/176-ai-agents-foundation-practitioner": "/courses/ai-agents/",
  "/w/uk/courses/177-ai-strategy-governance-foundation-and-practitioner": "/courses/ai-strategy-governance/",
  "/w/uk/courses/178-trusted-ai-safety-expert-taise": "/courses/taise/",
  "/w/uk/courses/18-certified-is0-27001-lead-implementer": "/courses/iso-27001-lead-implementer/",
  "/w/uk/courses/19-certified-iso-27001-lead-auditor": "/courses/iso-27001-lead-auditor/",
  "/w/uk/courses/22-certified-data-protection-officer-training-cdpo": "/courses/cdpo/",
  "/w/uk/courses/23-certified-gdpr-foundation": "/courses/gdpr-foundation/",
  "/w/uk/courses/25-certified-iso-31000-lead-risk-manager": "/courses/iso-31000-lead-risk-manager/",
  "/w/uk/courses/31-certified-iso-22301-lead-auditor": "/courses/iso-22301-lead-auditor/",
  "/w/uk/courses/32-certified-iso-22301-lead-implementer": "/courses/iso-22301-lead-implementer/",
  "/w/uk/courses/41-certified-information-privacy-technologist-cipt": "/courses/cipt/",
  "/w/uk/courses/42-certified-cybersecurity-manager": "/courses/cybersecurity-manager/",
  "/w/uk/courses/47-certified-iso-27701-lead-implementer": "/courses/iso-27701-lead-implementer/",
  "/w/uk/courses/63-gdpr-awareness-training": "/courses/gdpr-awareness/",
  "/w/uk/courses/92-iso-27005-information-security-risk-manager": "/courses/iso-27005-risk-manager/",
  "/w/uk/courses/94-certified-iso-31000-risk-analyst": "/courses/iso-31000-risk-analyst/",
  "/w/uk/courses/cat-16-data-protection": "/courses/data-protection/",
  "/w/uk/courses/cat-2-cybersecurity-courses": "/courses/cybersecurity/",
  "/w/uk/courses/cat-24-risk-management": "/courses/risk-management/",
  "/w/uk/courses/cat-27-it-governance-audit": "/courses/it-governance-audit/",
  "/w/uk/courses/cat-29-business-resilience-training": "/courses/business-resilience/",
  "/w/uk/courses/cat-30-iso-standards-training": "/courses/iso-standards/",
  "/w/uk/courses/cat-36-business-analysis-design": "/courses/business-analysis-design/",
  "/w/uk/courses/cat-41-compliance-training": "/courses/compliance-training/",
  "/w/uk/courses/cat-42-gdpr-training": "/courses/gdpr-training/",
  "/w/uk/courses/cat-53-iapp-training": "/courses/iapp-training/",
  "/w/uk/courses/cat-54-artificial-intelligence-training": "/courses/ai-training/",
  "/w/uk/courses/cat-56-disaster-recovery-business-continuity-training": "/courses/disaster-recovery/",
  "/w/uk/courses/cat-57-bcs-training-courses": "/courses/bcs-training/",
  "/w/uk/presenters": "/trainers/",
  "/w/uk/privacypolicy": "/privacy/",
  "/w/uk/privateevent": "/in-house-training/",
  "/w/uk/schedule": "/schedule/",
  "/w/uk/services": "/contact/",
  "/w/uk/termsandconditions": "/terms/",
  "/w/uk/upcoming": "/schedule/"
};

/* Anything not matched exactly. Order matters: first hit wins. */
const PREFIXES = [
  // Per-date event pages (.../courses/<id>-<slug>/<eventId>). A specific past
  // date has no lasting page of its own, so these land on the live schedule.
  ["/w/uk/courses/", "/schedule/"],
  ["/uk/courses/", "/courses/"],
  ["/w/uk/presenters/", "/trainers/"],
  ["/uk/presenters/", "/trainers/"],
  // Courses are live online now, so venue pages go to the schedule.
  ["/w/uk/venues/", "/schedule/"],
  ["/uk/venues/", "/schedule/"],
  ["/w/uk/", "/"],
  ["/uk/", "/"],
  // The eu/na/af regions were near-duplicates of the UK pages and are not being
  // rebuilt. They land on the closest UK equivalent rather than 404.
  ["/w/eu/", "/"], ["/w/na/", "/"], ["/w/af/", "/"],
  ["/eu/", "/"], ["/na/", "/"], ["/af/", "/"],
];

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const path = url.pathname.length > 1
    ? url.pathname.replace(/\/+$/, "")
    : url.pathname;

  for (const p of ARLO_PREFIXES) {
    if (path === p || path.startsWith(p + "/")) {
      return Response.redirect(ARLO + url.pathname + url.search, 301);
    }
  }

  const hit = EXACT[path];
  if (hit) return Response.redirect(url.origin + hit + url.search, 301);

  for (const [prefix, target] of PREFIXES) {
    if (path.startsWith(prefix)) {
      // Keep the query string, exactly as the EXACT and ARLO_PREFIXES branches do -
      // dropping it here was silently stripping gclid/UTM params off legacy paid links.
      return Response.redirect(url.origin + target + url.search, 301);
    }
  }

  return context.next();
}
