/* GENERATED by _build_pages.py - do not edit by hand.
   Courses withdrawn from Arlo. Their old addresses 301 to the category
   page so existing links and search results never hit a 404. */
export const WITHDRAWN = {};
